---
- name: Deploy To-Do List Application on EC2
  hosts: webservers
  become: yes
  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Remove conflicting containerd package
      apt:
        name: containerd
        state: absent

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu noble stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull the Docker image from Docker Hub
      docker_image:
        name: dohaelsawi/todo-app
        source: pull

    - name: Run the Docker container
      docker_container:
        name: todo-app
        image: dohaelsawi/todo-app
        state: started
        ports:
          - "8090:8090"  # Map port 8090 on the host to port 8090 in the container
        restart_policy: always  # Ensure the container restarts on reboot
